### PR TITLE
M4/mshivang010/profile page

### LINKED ISSUE #53: site wide database of users (Working with rajkive)
Details: The site-wide user database(Sequlize model) will include fields for user details such as username, password , email, and registration date(probably).

Purpose: The user database will store and manage information for all users across the application.  It will also aim to store the data such as completed excercises and flashcards in the database.

Expected outcomes: Seamless registration, login, and profile management for users, ensuring secure and personalized interactions.

### LINKED ISSUE #54: Profile Page
Details: Dynamically show the different aspects of the user profile like progress, trophies, achievements, exercises completed and flashcards.
Purpose: Enhance user experience, progress tracking and centralization of user data which would make it easier and more desirable for users to use the app and learn new languages.
Expected outcomes: Profile page that fetches data from database and dynamically renders it on the web app for the user to access. A simple and easy UI for progress tracking and revision of language concepts.

### PR DESCRIPTION
**Pull request by mshivang010**
Implement Backend and Database Support for all datatypes which are used in application.

### CODE REVIEW

**Review by rajkive — APPROVED** [review]
Everything looks properly set-up, aligns with the documentation and what was discussed as far as the appraoch goes. SqliteUserModel also aligns with the doc plus it has all the components that we are going to need to be stored in the user database. Looks good to merge.

**Review by mshivang010 — COMMENTED** [review]
Contributes towards issues: #53 and #54

**Review by mshivang010 — COMMENTED** [review]
Contributes towards issues: #53 and #54

**Review by mshivang010 — COMMENTED** [review]
Contributes towards issues: #53 and #54

**Review by mshivang010 — COMMENTED** [review]
Contributes towards issues: #53 and #54

**Pull request merged**
